USE [master]
GO

/****** Object:  Database [Школьный мир]    Script Date: 29.04.2025 14:22:55 ******/
CREATE DATABASE [Школьный мир]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Школьный мир', FILENAME = N'C:\Users\st310-05\Школьный мир.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Школьный мир_log', FILENAME = N'C:\Users\st310-05\Школьный мир_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Школьный мир].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Школьный мир] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Школьный мир] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Школьный мир] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Школьный мир] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Школьный мир] SET ARITHABORT OFF 
GO

ALTER DATABASE [Школьный мир] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Школьный мир] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Школьный мир] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Школьный мир] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Школьный мир] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Школьный мир] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Школьный мир] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Школьный мир] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Школьный мир] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Школьный мир] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Школьный мир] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Школьный мир] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Школьный мир] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Школьный мир] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Школьный мир] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Школьный мир] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Школьный мир] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Школьный мир] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Школьный мир] SET  MULTI_USER 
GO

ALTER DATABASE [Школьный мир] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Школьный мир] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Школьный мир] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Школьный мир] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Школьный мир] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Школьный мир] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Школьный мир] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Школьный мир] SET  READ_WRITE 
GO

